customhost = "employee.c1qkrvkwkomt.us-east-1.rds.amazonaws.com" 
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "cecelialimjieshi-employee"
customregion = "us-east-1"
